# Generated by Django 2.2.3 on 2019-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('salary', models.IntegerField(default=0)),
                ('expire_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('filled', models.BooleanField(default=False)),
                ('company', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('job_type', models.BooleanField(default=False)),
                ('category', models.BooleanField(default=False)),
            ],
        ),
    ]
