# Generated by Django 2.2.3 on 2019-07-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190716_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('education', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('expected_salary', models.IntegerField(default=0)),
                ('highest_education', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior')], default='Junior', max_length=200)),
                ('birth_date', models.DateField()),
                ('experience', models.TextField()),
                ('resume', models.CharField(max_length=16)),
                ('transcript', models.CharField(max_length=16)),
                ('image', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.CharField(default='', max_length=16),
        ),
    ]
