# Generated by Django 2.2.3 on 2019-07-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190716_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.CharField(default='Harrots', max_length=16),
        ),
    ]
