# Generated by Django 2.2.3 on 2019-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190717_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='highest_education',
            field=models.CharField(choices=[('Harrots', 'Harrots'), ('Eden', 'Eden'), ('Agen', 'Agen'), ('Adent', 'Adent')], default='Harrots', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Harrots', 'Harrots'), ('Eden', 'Eden'), ('Agen', 'Agen'), ('Adent', 'Adent')], default='Harrots', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(choices=[('Harrots', 'Harrots'), ('Eden', 'Eden'), ('Agen', 'Agen'), ('Adent', 'Adent')], default='Harrots', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Harrots', 'Harrots'), ('Eden', 'Eden'), ('Agen', 'Agen'), ('Adent', 'Adent')], default='Harrots', max_length=200),
        ),
    ]
