# Generated by Django 2.2.3 on 2019-07-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190717_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_website',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='from_hour',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='to_hour',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_day',
            field=models.IntegerField(choices=[('1', '1 day per week'), ('2', '2 day per week'), ('3', '3 day per week'), ('4', '4 day per week'), ('5', '5 day per week'), ('6', '6 day per week'), ('7', '7 day per week')], default='5'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resource'), ('Mar', 'Marketing'), ('Sale', 'Sales'), ('CS', 'Customer Services')], default='IT', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('F', 'Freelance'), ('I', 'Intern'), ('C', 'Contract')], default='P', max_length=1),
        ),
    ]
