# Generated by Django 2.2.3 on 2019-07-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190718_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_day',
            field=models.IntegerField(choices=[(1, '1 day per week'), (2, '2 day per week'), (3, '3 day per week'), (4, '4 day per week'), (5, '5 day per week'), (6, '6 day per week'), (7, '7 day per week')], default=5),
        ),
    ]
