# Generated by Django 2.2.3 on 2019-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190718_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='from_hour',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='to_hour',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
