# Generated by Django 2.2.3 on 2019-07-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20190718_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='job',
            name='to_hour',
        ),
        migrations.AddField(
            model_name='job',
            name='work_time',
            field=models.CharField(default='09:00-17:00', max_length=100),
        ),
    ]
