# Generated by Django 2.2.3 on 2019-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20190718_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(max_length=200, upload_to='uploads/company_logo'),
        ),
    ]
