# Generated by Django 2.2.3 on 2019-07-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20190718_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duty',
            field=models.TextField(default=''),
        ),
    ]
