# Generated by Django 2.2.3 on 2019-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
