# Generated by Django 2.2.3 on 2019-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20190721_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
