# Generated by Django 2.2.3 on 2019-07-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20190722_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='expected_salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('High School', 'High School or Equivalent'), ('Bachelor', "Bachelor's Degree"), ('Master', "Master's Degree"), ('Doctoral', 'Docteral Degrees')], default='Bachelor', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/image/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resume/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='uploads/transcript/'),
        ),
    ]
